#!/usr/bin/env bash

################################################################################
# Manifest for all metadata
################################################################################

# Define docker command and files
docker_cmd='docker'
docker_src='.'
arch=$(uname -m)
export version=$(cat version)

# Define the dockerfile, image name and tag (in order!)
declare -a BUILDS # Naming convention: <Dockerfile>#<Image>:<Tag>#build_args.
BUILDS+=( "server-ce/Dockerfile#ghcr.io/neerdoc/overleaf:${version}#--build-arg SHARELATEX_BASE_TAG=ghcr.io/neerdoc/overleaf-base:${version}" )

# We still need to define what image to run! Which we will assume is the last
# item we built!
TMP=$(echo "${BUILDS[-1]}" | awk -F'#' '{print $2}')
IMG=$(echo "${TMP}" | awk -F':' '{print $1}')
TAG=$(echo "${TMP}" | awk -F':' '{print $2}')
unset TMP
